# 向量模型

## 通义千问

In [1]:
from illufly.embeddings import ZhipuEmbeddings, DashScopeEmbeddings
from illufly.io import log
import os
# os.environ["ILLUFLY_CACHE_EMBEDDINGS"] = "./__CACHE_EMBEDDINGS__"

e = DashScopeEmbeddings()
e(
    docs=[
        "illufly？ 这是一个专注于写作和对话场景的多智能体框架",
        "普鸿是做消防业务的专业公司",
        "幻蝶AI的智能体框架非常领先",
    ],
    batch_mode=False,
    batch_size=30,
    verbose=True
)

[Document(text='illufly？ 这是一个专注于写作和对话场景的多智能体框架', metadata='{"source": "unknown", "embeddings": [-0.001326353983337494, -0.016058654738295187, 0.006714335641521
 ...(省略34081字)
 30237085, 0.009665492191539934, -0.036940965767791496, -0.019573379171582438, 0.018349285489644464]}'),
 Document(text='普鸿是做消防业务的专业公司', metadata='{"source": "unknown", "embeddings": [0.01901209119353509, 0.047613558120559216, 0.005663244291803186
 ...(省略34010字)
 043622673, 0.021550455358282188, 0.0029149522826230887, 0.020153073065567875, 0.013961002906109044]}'),
 Document(text='幻蝶AI的智能体框架非常领先', metadata='{"source": "unknown", "embeddings": [0.011582608051240808, 0.005565467917783711, -0.0333123727285686
 ...(省略33964字)
 2410607, 0.014069898882757264, -0.035663543166320526, -0.020232440345917438, -0.010171905788589685]}')]

In [23]:
import numpy as np

d = 128  # 向量的维度
n = 10000  # 向量的数量
data = np.random.random((n, d)).astype('float32')  # 创建随机向量
data

print("data: ", data)

import faiss

index = faiss.IndexFlatL2(d)  # L2距离度量的平面索引
index.add(data)  # 将数据添加到索引中

k = 5  # 查找最相似的前5个向量
query_vector = np.random.random((1, d)).astype('float32')  # 创建一个查询向量
distances, indices = index.search(query_vector, k)  # 搜索

print(f"Nearest neighbors (indices): {indices}")
print(f"Distances: {distances}")

# vectors = np.array([doc.metadata['embeddings'] for doc in e.output])

data:  [[0.2948229  0.82961154 0.47127348 ... 0.6672886  0.82751054 0.34681177]
 [0.6373704  0.86194396 0.7850018  ... 0.77993435 0.06357363 0.54621   ]
 [0.22330941 0.27790442 0.24501505 ... 0.0368644  0.12274551 0.775946  ]
 ...
 [0.5128865  0.76793176 0.46633238 ... 0.6367985  0.9986108  0.7562756 ]
 [0.43221545 0.2550714  0.53636205 ... 0.40218335 0.31730047 0.45858368]
 [0.09664652 0.20799264 0.12496893 ... 0.73829806 0.7290184  0.66596776]]
Nearest neighbors (indices): [[3795 3273 6543 8073 8454]]
Distances: [[13.356586 13.396664 13.531391 13.568047 13.654969]]


In [21]:
indices

array([[6911, 1788,  154, 9048, 3168]])

In [1]:
from illufly.embeddings import DashScopeEmbeddings
import os

e = DashScopeEmbeddings()
x = e(
    docs=[
"illufly？ 这是一个专注于写作和对话场景的多智能体框架",
"普鸿是做消防业务的专业公司",
"幻蝶AI的智能体框架非常领先",
'模型：这里列出了被评估的模型名称，都是基于"text-embedding-v3"',
'模型维度：这是指向量模型的维度，即每个向量在嵌入空间中的特征数量。在这个例子中，模型的维度分别为1024、768和512。',
'MTEB：这可能是模型在某个基准测试（可能是多任务情感分析基准，Multi-Task Emotion Benchmark）上的总体准确率或得分。数值越高，表示模型在该基准测试上的表现越好。',
'MTEB（Retrieval task）：这是模型在MTEB基准的检索任务上的得分。检索任务通常涉及到从数据集中检索与给定查询最相关的项。',
'CMTEB：这可能是模型在某种上下文修改的MTEB基准测试上的得分。这里的“C”可能代表“Contextual”或其他某种修改版。',
'CMTEB (Retrieval task)：这是模型在CMTEB基准的检索任务上的得分。',
"illufly？ 这是一个专注于写作和对话场景的多智能体框架",
"普鸿是做消防业务的专业公司",
"幻蝶AI的智能体框架非常领先",
'模型：这里列出了被评估的模型名称，都是基于"text-embedding-v3"',
'模型维度：这是指向量模型的维度，即每个向量在嵌入空间中的特征数量。在这个例子中，模型的维度分别为1024、768和512。',
'MTEB：这可能是模型在某个基准测试（可能是多任务情感分析基准，Multi-Task Emotion Benchmark）上的总体准确率或得分。数值越高，表示模型在该基准测试上的表现越好。',
'MTEB（Retrieval task）：这是模型在MTEB基准的检索任务上的得分。检索任务通常涉及到从数据集中检索与给定查询最相关的项。',
'CMTEB：这可能是模型在某种上下文修改的MTEB基准测试上的得分。这里的“C”可能代表“Contextual”或其他某种修改版。',
'CMTEB (Retrieval task)：这是模型在CMTEB基准的检索任务上的得分。',
"illufly？ 这是一个专注于写作和对话场景的多智能体框架",
"普鸿是做消防业务的专业公司",
"幻蝶AI的智能体框架非常领先",
'模型：这里列出了被评估的模型名称，都是基于"text-embedding-v3"',
'模型维度：这是指向量模型的维度，即每个向量在嵌入空间中的特征数量。在这个例子中，模型的维度分别为1024、768和512。',
'MTEB：这可能是模型在某个基准测试（可能是多任务情感分析基准，Multi-Task Emotion Benchmark）上的总体准确率或得分。数值越高，表示模型在该基准测试上的表现越好。',
'MTEB（Retrieval task）：这是模型在MTEB基准的检索任务上的得分。检索任务通常涉及到从数据集中检索与给定查询最相关的项。',
'CMTEB：这可能是模型在某种上下文修改的MTEB基准测试上的得分。这里的“C”可能代表“Contextual”或其他某种修改版。',
'CMTEB (Retrieval task)：这是模型在CMTEB基准的检索任务上的得分。',
    ],
    batch_mode=False,
    batch_size=30,
    verbose=True
)

In [5]:
import time
start = time.time()
from illufly.vectordb import FaissDB
v = FaissDB(e, train=False)
v.query("幻蝶是啥？")
end = time.time()
print("耗时{}s".format(end-start))

耗时0.0027799606323242188s


In [10]:
start = time.time()
v = FaissDB(e, train=True)
v.query("幻蝶是啥？")
end = time.time()
print("耗时{}s".format(end-start))

耗时0.0030438899993896484s


In [11]:
start = time.time()
v.query("幻蝶是啥？")
end = time.time()
print("耗时{}s".format(end-start))

耗时0.00015497207641601562s


In [12]:
from illufly.embeddings import ZhipuEmbeddings, DashScopeEmbeddings
from illufly.io import log
import os

e = DashScopeEmbeddings()
e(
    docs=[
        "illufly？ 这是一个专注于写作和对话场景的多智能体框架",
        "幻蝶AI的智能体框架非常领先",
    ],
    batch_mode=False,
    verbose=True
)

[Document(text='illufly？ 这是一个专注于写作和对话场景的多智能体框架', metadata='{"source": "unknown", "embeddings": [-0.0847005844116211, 0.04371895268559456, 0.000247611606027931,...省略22681字'),
 Document(text='幻蝶AI的智能体框架非常领先', metadata='{"source": "unknown", "embeddings": [-0.05167926475405693, 0.00564523134380579, -0.00589442625641822...省略22669字')]

In [13]:
from illufly.embeddings import ZhipuEmbeddings, DashScopeEmbeddings
from illufly.io import log

e = DashScopeEmbeddings()
e.query("illufly 是一个专注于写作和对话场景的多智能体框架")

[-0.08643536269664764,
 0.04660885035991669,
 0.015427844598889351,
 -0.04164039343595505,
 -0.07397478818893433,
 -0.011376187205314636,
 0.006304221693426371,
 0.04455837607383728,
 -0.0052001201547682285,
 -0.007955444976687431,
 -0.001227326923981309,
 -0.0009322016849182546,
 0.006673898547887802,
 0.0005347991245798767,
 0.018828870728611946,
 -0.018947167322039604,
 0.005155758932232857,
 -0.017705054953694344,
 0.029948750510811806,
 -0.05772873014211655,
 -0.03272872045636177,
 -0.032590705901384354,
 -0.034858059138059616,
 -0.00233635725453496,
 0.03036278858780861,
 0.12153001874685287,
 -0.0472397655248642,
 -0.040615156292915344,
 0.008739159442484379,
 -0.02233833633363247,
 0.05272084102034569,
 -0.012460572645068169,
 0.02352130226790905,
 -0.0020578675903379917,
 -0.007363962009549141,
 -0.03598187491297722,
 0.033063892275094986,
 -0.003583400510251522,
 -0.09463725984096527,
 0.016265779733657837,
 0.002715892158448696,
 0.0346214659512043,
 0.015851741656661034,
 -

## 智谱AI

In [ ]:
from illufly.embeddings import ZhipuEmbeddings, DashScopeEmbeddings
from illufly.io import log

e = ZhipuEmbeddings()
resp = e.embed_documents(["illufly 是一个专注于写作和对话场景的多智能体框架"])
print(resp)

In [ ]:
from illufly.embeddings import ZhipuEmbeddings, DashScopeEmbeddings
from illufly.io import log

e = ZhipuEmbeddings()
resp = e.query("illufly 是一个专注于写作和对话场景的多智能体框架")
print(resp)