In [2]:
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv(), override=True)
import os
os.chdir('..')

## 文本向量编码

你可以使用向量数据库执行三种搜索类型（"similarity"，"similarity_score_threshold"，"mmr"），都是基于向量空间模型的搜索方法，它们的主要区别在于如何从向量空间中选择相关的文档：

1. "similarity"：这种搜索类型基于余弦相似度，它会计算查询向量和每个文档向量之间的相似度，然后返回最相似的文档。这种方法的优点是简单直观，但是可能会返回很多与查询非常相似的文档，这可能会导致结果的多样性不足。

2. "similarity_score_threshold"：这种搜索类型也是基于余弦相似度，但是它会设置一个相似度阈值，只有当文档和查询的相似度超过这个阈值时，才会返回这个文档。这种方法可以帮助过滤掉与查询不太相关的文档，但是设置合适的阈值可能会比较困难。

3. "mmr"：这种搜索类型基于最大边缘相关性（Maximal Marginal Relevance）算法，它不仅考虑文档和查询的相似度，还考虑文档之间的相似度。这种方法的目标是在保证结果的相关性的同时，增加结果的多样性。这种方法可以避免返回很多相似的文档，但是计算复杂度可能会比较高。


```python
    # Retrieve more documents with higher diversity
    # Useful if your dataset has many similar documents
    docsearch.as_retriever(
        search_type="mmr",
        search_kwargs={'k': 6, 'lambda_mult': 0.25}
    )

    # Fetch more documents for the MMR algorithm to consider
    # But only return the top 5
    docsearch.as_retriever(
        search_type="mmr",
        search_kwargs={'k': 5, 'fetch_k': 50}
    )

    # Only retrieve documents that have a relevance score
    # Above a certain threshold
    docsearch.as_retriever(
        search_type="similarity_score_threshold",
        search_kwargs={'score_threshold': 0.8}
    )

    # Only get the single most similar document from the dataset
    docsearch.as_retriever(search_kwargs={'k': 1})

    # Use a filter to only retrieve documents from a specific paper
    docsearch.as_retriever(
        search_kwargs={'filter': {'paper_title':'GPT-4 Technical Report'}}
    )
```

In [ ]:
!pip install -U langchain-community faiss-cpu langchain-openai tiktoken

In [29]:
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings.sentence_transformer import (
    SentenceTransformerEmbeddings,
)

embedding_function = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")
db = FAISS.from_texts([
    "今天零下5度",
    "查询气温",
    "这几天有几度？",
    "冻不？",
    "查询气温",
    "这几天有几度？",
    "冻不？",
    "我是基于Transformer的文本识别模型",
    "今天我过生日",
    "请问你的模型参数",
    "我们提供AI知识培训",
    "你们有哪些服务",
    "能给我你的产品列表？",
    ], embedding_function)

In [30]:
db.similarity_search("今天冷吗", k=5)

[Document(page_content='这几天有几度？'),
 Document(page_content='这几天有几度？'),
 Document(page_content='今天零下5度'),
 Document(page_content='今天我过生日'),
 Document(page_content='你们有哪些服务')]

In [31]:
db.similarity_search("冷吗", k=5)

[Document(page_content='查询气温'),
 Document(page_content='查询气温'),
 Document(page_content='请问你的模型参数'),
 Document(page_content='你们有哪些服务'),
 Document(page_content='能给我你的产品列表？')]

In [32]:
user_query = "今天冷吗"
db.similarity_search_with_score(user_query, k=7)

[(Document(page_content='这几天有几度？'), 0.24982345),
 (Document(page_content='这几天有几度？'), 0.24982345),
 (Document(page_content='今天零下5度'), 0.3001034),
 (Document(page_content='今天我过生日'), 0.58030474),
 (Document(page_content='你们有哪些服务'), 0.76883394),
 (Document(page_content='请问你的模型参数'), 0.8504981),
 (Document(page_content='查询气温'), 0.85196805)]

In [33]:
result = db.max_marginal_relevance_search(user_query, k=10)
result

[Document(page_content='这几天有几度？'),
 Document(page_content='查询气温'),
 Document(page_content='今天零下5度'),
 Document(page_content='今天我过生日'),
 Document(page_content='我是基于Transformer的文本识别模型'),
 Document(page_content='冻不？'),
 Document(page_content='我们提供AI知识培训'),
 Document(page_content='你们有哪些服务'),
 Document(page_content='这几天有几度？'),
 Document(page_content='请问你的模型参数')]

## ReRank

In [34]:
from sentence_transformers import CrossEncoder

model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2', max_length=512)

scores = model.predict([(user_query, r.page_content) for r in result])
# 按得分排序
sorted_list = sorted(
    zip(scores, result), key=lambda x: x[0], reverse=True
)

sorted_list

[(7.106229, Document(page_content='这几天有几度？')),
 (7.106229, Document(page_content='这几天有几度？')),
 (6.605303, Document(page_content='今天零下5度')),
 (6.140743, Document(page_content='今天我过生日')),
 (4.64846, Document(page_content='你们有哪些服务')),
 (2.1951842, Document(page_content='请问你的模型参数')),
 (1.3442535, Document(page_content='查询气温')),
 (0.53288954, Document(page_content='我们提供AI知识培训')),
 (0.3154126, Document(page_content='我是基于Transformer的文本识别模型')),
 (-5.020375, Document(page_content='冻不？'))]

In [ ]:
model.predict([
    ("什么气温？", "今天零下5度"),
    ("什么气温？", "查询气温"),
    ("什么气温？", "今天几度？"),
])

array([-1.9662569,  1.0652385,  5.578872 ], dtype=float32)

In [ ]:
model.predict([
    ("冷吗？", "今天零下5度"),
    ("冷吗？", "查询气温"),
    ("冷吗？", "今天冻不？"),
])

array([-1.4098096 ,  0.12893607,  5.7321796 ], dtype=float32)

In [ ]:
model.predict([
    ("你是什么模型？", "我是基于Transformer的文本识别模型"),
    ("你是什么模型？", "请问你的模型参数"),
])

array([0.3885294, 2.6159494], dtype=float32)

In [ ]:
model.predict([
    ("你们公司有什么产品？", "我们提供AI知识培训"),
    ("你们公司有什么产品？", "你们有哪些服务"),
    ("你们公司有什么产品？", "能给我你的产品列表？"),
])

array([-2.2944603 ,  0.83219373,  1.2929248 ], dtype=float32)

In [4]:
from langchain_zhipu import ChatZhipuAI, ZhipuAIEmbeddings
from langchain_chinese import (
    LocalFilesLoader,
    create_qa_chain,
    create_qa_toolkits,
    create_reason_agent,
)
from langchain_community.vectorstores import Chroma

docs = LocalFilesLoader()
chunks = docs.load_and_split()

db = Chroma.from_documents(chunks, ZhipuAIEmbeddings())

chain = create_qa_chain(ChatZhipuAI(), db.as_retriever())

In [7]:
!pip show chromadb

Name: chromadb
Version: 0.4.24
Summary: Chroma.
Home-page: 
Author: 
Author-email: Jeff Huber <jeff@trychroma.com>, Anton Troynikov <anton@trychroma.com>
License: 
Location: /Users/xuehongwei/Library/Caches/pypoetry/virtualenvs/langchain-chinese-gSQlHcwW-py3.9/lib/python3.9/site-packages
Requires: bcrypt, build, chroma-hnswlib, fastapi, grpcio, importlib-resources, kubernetes, mmh3, numpy, onnxruntime, opentelemetry-api, opentelemetry-exporter-otlp-proto-grpc, opentelemetry-instrumentation-fastapi, opentelemetry-sdk, orjson, overrides, posthog, pulsar-client, pydantic, pypika, PyYAML, requests, tenacity, tokenizers, tqdm, typer, typing-extensions, uvicorn
Required-by: 


In [5]:
chain.invoke("供应商达标的业绩要求是什么")

AIMessage(content='应商在提交申请材料时需要满足哪些基本资质要求？\n\n回答: 供应商在提交申请材料时需要满足以下基本资质要求：\n1. 具备合法有效的营业执照。\n2. 必须具备税务登记证，并符合国家税收法律法规。\n3. 拥有有效的组织机构代码证。', response_metadata={'finish_reason': 'stop'})

In [8]:
for chunk in chain.stream("请从资料中确认供应商达标的标准是什么"):
    # print(type(chunk))
    print(chunk)

content='根据'
content='提供的'
content='资料'
content='，'
content='供应商'
content='达标'
content='的标准'
content='如下'
content='：\n\n1'
content='.'
content=' 基'
content='本'
content='资质'
content='要求'
content='：\n  '
content=' -'
content=' 具'
content='备'
content='合法'
content='有效的'
content='营业执照'
content='。\n  '
content=' -'
content=' 拥'
content='有'
content='税务'
content='登记'
content='证'
content='，'
content='并'
content='符合'
content='国家'
content='税收'
content='法律法规'
content='。\n  '
content=' -'
content=' 拥'
content='有'
content='有效的'
content='组织'
content='机构'
content='代码'
content='证'
content='。\n\n2'
content='.'
content=' 经营'
content='和'
content='财务'
content='能力'
content='：\n  '
content=' -'
content=' 与'
content='公司'
content='合作的'
content='月份'
content='，'
content='经'
content='公司'
content='销售'
content='的产品'
content='月'
content='总价'
content='不得'
content='低于'
content='人民币'
content='3'
content='万元'
content='。\n  '
content=' -'
content=' 具'
content='备'
content='健全'
content='和'
content='稳定的'
content='财务'
conten

In [4]:
async for chunk in chain.astream_events("供应商达标的业绩要求是什么?", version="v1"):
	# print(chunk)
	# print(chunk['event'])
	if(chunk['event'] == "on_chat_model_stream"):
		print(chunk['data']['chunk'].content, end="|", flush=True)
	elif(chunk['event'] == "on_retriever_end"):
		for doc in chunk['data']['output']['documents']:
			print(doc.metadata['source'])


/Users/xuehongwei/Library/Caches/pypoetry/virtualenvs/langchain-chinese-gSQlHcwW-py3.9/lib/python3.9/site-packages/langchain_core/_api/beta_decorator.py:86: LangChainBetaWarning: This API is in beta and may change in the future.
  warn_beta(


/Users/xuehongwei/github/wencheng/data/documents/autogpt-demo/供应商资格要求.pdf
/Users/xuehongwei/github/wencheng/data/documents/autogpt-demo/供应商资格要求.pdf
/Users/xuehongwei/github/wencheng/data/documents/autogpt-demo/求职简历.docx
/Users/xuehongwei/github/wencheng/data/documents/autogpt-demo/供应商资格要求.pdf
供应商|达|标的|业绩|要求|主要包括|：

1|.| 月|销售额|：|供应商|需|保证|在与|本公司|合作的|月份|中|，|经|我|方|销售|的产品|月|总价|不得|低于|人民币|3|万元|。

2|.| 稳|定的|财务|状况|：|供应商|应|具备|健全|和|稳定的|财务|状况|，|以及|良好的|信用|记录|。

3|.| 行|业|经验|：|供应商|应|具有|至少|五|年的|相关|行业|经验|。

4|.| 业务|声誉|：|供应商|应有|良好的|业务|声誉|和|客户|满意度|记录|。

这些|业绩|要求|旨在|确保|供应商|具备|良好的|经营|能力|、|稳定的|财务|状况|和|丰富的|行业|经验|，|以满足|合作|的需要|。||

In [4]:
llm_zhipu = ChatZhipuAI(model="glm-4")
tools = create_qa_toolkits(qa_chain=chain)
agent = create_reason_agent(llm_zhipu, tools=tools)

In [6]:
from langchain.tools.render import render_text_description, render_text_description_and_args
print(render_text_description_and_args(tools))
print(render_text_description(tools))

ask_document: 根据资料库回答问题。考虑上下文信息，确保问题对相关概念的定义表述完整。
    args:
    - query 类型是str, 用户问题的文字描述
    , args: {'query': {'title': '提问内容', 'description': '用户问题的文字描述，必须是字符串', 'type': 'string'}}
ask_document: 根据资料库回答问题。考虑上下文信息，确保问题对相关概念的定义表述完整。
    args:
    - query 类型是str, 用户问题的文字描述
    


In [8]:
tools[0].invoke("供应商怎样才算合格？")

AIMessage(content='供应商要算合格，需要满足以下条件：\n\n1. **基本资质要求**：\n   - 拥有合法有效的营业执照。\n   - 具备税务登记证，并符合国家税收法律法规。\n   - 拥有有效的组织机构代码证。\n\n2. **经营和财务能力**：\n   - 在与公司合作的月份中，经公司销售的产品月总价不得低于人民币3万元。\n   - 具备健全和稳定的财务状况，以及良好的信用记录。\n   - 拥有足够的流动资金来支持合同执行。\n\n3. **产品和服务质量**：\n   - 供应的产品必须符合国家及行业标准，并通过相关质量认证。\n   - 拥有高标准的服务体系，并承诺在合作期间提供持续、稳定、优质的服务。\n\n4. **行业经验和声誉**：\n   - 具有至少五年的相关行业经验。\n   - 拥有良好的业务声誉和客户满意度记录。\n\n5. **环境保护和社会责任**：\n   - 遵循环境保护法律法规，在经营活动中实施环保措施。\n   - 积极承担社会责任，遵守劳工权益法律法规，并推行公平、平等、安全和健康的劳动环境。\n\n6. **申请和审核流程**：\n   - 按规定提交完整的申请材料。\n   - 通过公司的初步审核、现场考察及终审决定。\n\n只有当供应商满足上述所有条件，才能被认为是合格的供应商，并有机会参与投标。')

In [6]:
await tools[0].ainvoke("供应商怎样才算合格？")

"content='供应商合格的标准如下：\\n\\n一、基本资质要求\\n1. 具备合法有效的营业执照。\\n2. 具备税务登记证，并符合国家税收法律法规。\\n3. 拥有有效的组织机构代码证。\\n\\n二、经营和财务能力\\n1. 具备健全和稳定的财务状况，以及良好的信用记录。\\n2. 拥有足够的流动资金来支持合同执行。\\n3. 合作的月份，经我方销售的产品月总价不得低于人民币3万元。\\n\\n三、产品和服务质量\\n1. 提供的产品必须符合国家及行业标准，并通过相关质量认证。\\n2. 具备高标准的服务体系，并承诺在合作期间提供持续、稳定、优质的服务。\\n\\n四、行业经验和声誉\\n1. 具有至少五年的相关行业经验。\\n2. 有良好的业务声誉和客户满意度记录。\\n\\n五、社会责任和可持续性\\n1. 应遵循环境保护法律法规，并在经营活动中实施环保措施。\\n2. 积极承担社会责任，遵守劳工权益法律法规，并推行公平、平等、安全和健康的劳动环境。\\n\\n只有当供应商满足以上所有标准，才能被认为是合格的供应商。'"

In [5]:
from langchain.agents import AgentExecutor
agent_executor = AgentExecutor(agent=agent, tools=tools)

In [8]:
for chunk in agent_executor.stream({"input": "供应商怎样才算合格？"}):
    print(chunk)

{'actions': [AgentAction(tool='ask_document', tool_input={'query': '供应商评价体系和合格分数线是什么？'}, log='### 关键概念:\n- 供应商合格标准\n\n### 概念拆解:\n- 供应商合格标准 - \n  - 供应商评价体系\n  - 合格分数线\n  - 评价项目\n\n### 反思:\n- 需要了解是否有现成的供应商评价体系。\n- 要确定是否已有合格分数线或评价项目的具体信息。\n\n### 思考:\n- 我需要先了解整个供应商评价体系，才能确定合格的标准。\n- 评价体系和合格分数线可能来源于相同或不同的数据源，尝试一次性获取。\n- 如果没有直接的数据源，我可能需要拆解评价体系，单独查询各个评价项目。\n\n### 推理:\n- 通过资料库查询“供应商评价体系”及“合格分数线”的相关信息。\n\n### 计划:\n- 使用 `ask_document` 工具查询“供应商评价体系”及“合格分数线”。\n\n### 输出所选择执行的动作/工具/指令:\n```json\n{"name": "ask_document", "args": {"query": "供应商评价体系和合格分数线是什么？"}}\n```')], 'messages': [AIMessage(content='### 关键概念:\n- 供应商合格标准\n\n### 概念拆解:\n- 供应商合格标准 - \n  - 供应商评价体系\n  - 合格分数线\n  - 评价项目\n\n### 反思:\n- 需要了解是否有现成的供应商评价体系。\n- 要确定是否已有合格分数线或评价项目的具体信息。\n\n### 思考:\n- 我需要先了解整个供应商评价体系，才能确定合格的标准。\n- 评价体系和合格分数线可能来源于相同或不同的数据源，尝试一次性获取。\n- 如果没有直接的数据源，我可能需要拆解评价体系，单独查询各个评价项目。\n\n### 推理:\n- 通过资料库查询“供应商评价体系”及“合格分数线”的相关信息。\n\n### 计划:\n- 使用 `ask_document` 工具查询“供应商评价体系”及“合格分数线”。\n\n### 输出所选择执行的动作/工具/指令:\n```json\n{"name": "ask_

In [10]:
async for chunk in agent_executor.astream_events({"input": "供应商怎样才算合格？"}, version="v1"):
    event = chunk['event']
    if(event == "on_chat_model_stream"):
        if('chunk' in chunk['data']):
            print(chunk['data']['chunk'].content, end="", flush=True)
    elif(event == "on_chain_end"):
        print(event)
        print(chunk['data']['output'])
    else:
        print(event)

on_chain_start
on_chain_start
on_chain_start
on_chain_stream
on_chain_start
on_chain_start
on_chain_stream
on_chain_stream
on_chain_stream
on_chain_end

on_chain_end
{'agent_scratchpad': ''}
on_chain_end
{'input': '供应商怎样才算合格？', 'intermediate_steps': [], 'agent_scratchpad': ''}
on_prompt_start
on_prompt_end
on_chat_model_start
### 关键概念:
- 供应商合格标准

### 概念拆解:
- 供应商合格标准 - 
  - 供应商评价体系
  - 合格分数线
  - 评价具体指标

### 反思:
- 需要了解是否有现成的供应商评价体系。
- 要确定是否已经有具体的合格分数线和评价指标。

### 思考:
- 首先，需要了解供应商评价体系是否存在，如果存在，需要获取这个体系的具体内容。
- 其次，要明确合格的标准，即合格分数线和评价的具体指标。

### 推理:
- 可以通过查询资料库来获取有关供应商评价体系的信息。

### 计划:
- 使用 `ask_document` 工具查询供应商评价体系的相关信息。

### 输出所选择执行的动作/工具/指令:
```json
{"name": "ask_document", "args": {"query": "供应商评价体系包括哪些标准和指标？"}}
```on_chat_model_end
on_parser_start
on_parser_end
on_chain_stream
on_chain_end
tool='ask_document' tool_input={'query': '供应商评价体系包括哪些标准和指标？'} log='### 关键概念:\n- 供应商合格标准\n\n### 概念拆解:\n- 供应商合格标准 - \n  - 供应商评价体系\n  - 合格分数线\n  - 评价具体指标\n\n### 反思:\n- 需要了解是否有现成的供应商评价体系。\n- 要确定是否已经有具体的合格